### ISSUE TITLE
希望AI翻译能自定义提示词

### ISSUE THREAD

**Issue by Dango998** [MoyouDE/ATranslator-Homepage#1]
目前的提示词无法改动，为了提升翻译效果，建议增加自定义提示词功能。
以及，AI反回的结果超过一行，应该被判定为无效翻译。
通常这种情况，AI都没有给出正确反馈，当然不排除有人会一次翻译多行，所以作为可以勾选的选项是个不错的办法。

**Comment by MoyouDE** [comment]
关于chatgpt的设置优化，会计划增加以下功能：
-  __提示词自定义功能__  
- __填写自定义接口时的完整url预览__   

至于返回多行被判定为无效暂时有待考虑：  
目前翻译多行是正常的使用场景，不排除会有多行单行混杂的情况，这种情况给出全局的校验不太合适。  
由于大模型翻译结果不稳定，后续会再考虑其是否需要添加其他自动校验方式。
目前还是请按照批量翻译 逐一检查然后手动矫正的工作流来操作。

**Comment by MoyouDE** [comment]
1.2.0已实现
